# Copyright Red Hat

name: Publish

on:
  push:
    branches: [ make-publish ]

jobs:
  publish:
    if: github.repository_owner == 'chrisahl'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install Dependencies and Publish
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: |
        export VERSION="0.0.1-$(date -u +'%Y%m%d-%H-%M-%S')-${GITHUB_SHA::7}-${GITHUB_REF_NAME}"
        make publish PUSH_LATEST=true
